BCKLG-2: Add basic API
themilchenko/cyber_bed pull request #3
Opened 2023-10-14 12:33 UTC by themilchenko

2023-10-16 16:10 UTC, zeronethunter commented on internal/app/init.go
> +	v1.GET("/get/plants/:userID", s.plantsHandler.GetPlants)
:userID/plants/get

2023-10-16 16:13 UTC, zeronethunter commented on internal/auth/delivery/auth_handlers.go
> +	user, err := h.usersUsecase.GetBySessionID(cookie.Value)
зачем получать всего юзера, когда нужон только айдишник

2023-10-16 16:33 UTC, zeronethunter requested changes

2023-10-16 16:33 UTC, zeronethunter commented on internal/auth/delivery/auth_handlers.go
> +func (h AuthHandler) Auth(c echo.Context) error {
Тут нужно сначала ходить в базу за юзером, а потом уже смотреть за авторизацией, и если ее нет, то создать

2023-10-16 16:33 UTC, zeronethunter commented on internal/auth/delivery/auth_handlers.go
> +	session, err := h.authUsecase.Login(authUsr.Username, authUsr.Password)
тут сразу выводи userID чтобы избавиться от лишнего похода в бд

2023-10-16 16:33 UTC, zeronethunter commented on internal/auth/delivery/auth_utils.go
> +var deleteExpire = map[string]int{
перенеси в модели auth.go

2023-10-16 16:33 UTC, zeronethunter commented on internal/auth/delivery/auth_utils.go
> +	cookieName = "seesion_id"
seesion_id - написал какашку

2023-10-16 16:33 UTC, zeronethunter commented on internal/auth/delivery/auth_utils.go
> +	return &http.Cookie{
хранимки в конфиг плз и передавай эти поля прям в деливери

2023-10-16 16:33 UTC, zeronethunter commented on internal/auth/delivery/auth_utils.go
> +		return nil, tracerr.Wrap(err)
лучше пока без tracerr, он не нужен будет, если будем красива вропить ошибки

2023-10-16 16:33 UTC, zeronethunter commented on internal/auth/repository/auth_repository.go
> +	res := db.DB.Table(models.SessionTable).Create(&cookie)
`db.DB.Table(models.Session)` - вынеси в отдельное поле в репе, потому что юзается во всех функиях
создавай на уровне NewRepository....()

2023-10-16 16:33 UTC, zeronethunter commented on internal/auth/usecase/auth_usecase.go
> +		Value:      uuid.New().String(),
в конфиг

2023-10-16 16:33 UTC, zeronethunter commented on internal/auth/usecase/auth_usecase.go
> +		return err
глянь в другом мре, `errors.Wrap(err error, msg string)`

2023-10-16 16:33 UTC, zeronethunter commented on internal/auth/usecase/auth_usecase.go
> +		return err
и везде врапи, чтобы потом удобно сделать логгирование и вывод юзеру

схема такая: когда ошибка есть, но не в функции, то есть наша ошибка типа `models.ErrAuth`, то прокидывай так:
```go
return errors.Wrapf(models.ErrAuth, "failed to get credentials of user with id %d", u.UserID)
```
а когда ошибка есть
```go
return errors.Wrap(err, "failed to fetch plant data")
```

старайся делать так, чтобы при unwrap ошибки было как можно больше информации о конкретном кейсе типа

failed to get plant: failed to auth user with id 47: failed to connect to db: unknown code 447

короче где разумно лучше делать Wrapf с определяющей инфой

2023-10-16 16:33 UTC, zeronethunter commented on internal/auth/usecase/auth_usecase.go
> +	if err := u.authRepository.DeleteBySessionID(sessionID); err != nil {
сразу делай
```go
return errors.Wrapf(u.authRepository.DeleteBySessionID(sessionID), "failed to delete user by session id %s", sessionID)
```

2023-10-16 19:54 UTC, themilchenko commented on internal/auth/delivery/auth_handlers.go
> +func (h AuthHandler) Auth(c echo.Context) error {
Так это же GET запрос, сессия создается  в login

2023-10-16 20:06 UTC, themilchenko commented on internal/auth/delivery/auth_utils.go
> +	return &http.Cookie{
Не очень понял, что конкретно?

2023-10-17 09:51 UTC, zeronethunter commented on internal/auth/delivery/auth_handlers.go
> +func (h AuthHandler) Auth(c echo.Context) error {
тогда надо редиректить на фронте на логин

2023-10-17 09:54 UTC, zeronethunter commented on internal/auth/delivery/auth_utils.go
> +	return &http.Cookie{
вынеси в конфиг захардкоженные поля, чтобы изи можно было менять параметры куки
сделай функу такую мб
```go
func makeHTTPCookie(sessionID string, opts CookieOpts) {
 return &http.Cookie{
  x1: opts.x1,
  x2: opts.x2,
  ...
 }
}
```
и ее в деливери, н или где она юзайется, и чистай CookieOpts из конфига

2023-10-17 09:55 UTC, zeronethunter commented on internal/auth/delivery/auth_utils.go
> +	return &http.Cookie{
а можно ваще
```go
func (d delivery) makeHTTPCookie(sessionID string) {
 return &http.Cookie{
  x1: d.cookieOpts.x1,
  x2: d.cookieOpts.x2,
  ...
 }
}
```

2023-10-17 09:57 UTC, themilchenko commented on internal/auth/delivery/auth_utils.go
> +	return &http.Cookie{
сделал в последнем коммите

2023-10-17 09:57 UTC, zeronethunter commented on internal/auth/delivery/auth_utils.go
> +			AddDate(int(h.config.CookieSettings.ExpireDate.Years),
прокидывай в хендлер сразу CookieSettings, зачем весь конфиг прокидывать, если не юзаешь его

2023-10-17 09:58 UTC, zeronethunter commented on internal/auth/usecase/auth_usecase.go
> +	if err := u.authRepository.DeleteBySessionID(sessionID); err != nil {
не поправил

2023-10-17 09:59 UTC, themilchenko commented on internal/auth/delivery/auth_utils.go
> +			AddDate(int(h.config.CookieSettings.ExpireDate.Years),
ок, согласен

2023-10-17 10:00 UTC, zeronethunter commented on internal/users/usecase/users_usecase.go
> +			models.ErrUserExists,
не прокинул ошибку сверху

2023-10-17 10:00 UTC, zeronethunter commented on internal/users/usecase/users_usecase.go
> +		return 0, err
🗿

2023-10-17 10:03 UTC, zeronethunter commented on internal/users/usecase/users_usecase.go
> +			models.ErrUserExists,
если хочешь проверить, что юзер не существует, но стоит проверять конкретную ошибку горма через 
```go
// gorm.ErrConflict - пример, подебаж за ошибкой наверн
if errors.Is(err, gorm.ErrConflict) {
  return 0, errors.Wrap(models.ErrUserExists, "conflict user already exists")
}
```

2023-10-17 10:04 UTC, zeronethunter commented on internal/users/usecase/users_usecase.go
> +			models.ErrUserExists,
потому что может упасть база и мы не залогируем ошибку

2023-10-17 19:25 UTC, merged