BCKLG-3: ai plant recognition
themilchenko/cyber_bed pull request #4
Opened 2023-10-14 17:18 UTC by zeronethunter

2023-10-14 17:20 UTC, zeronethunter commented on internal/recognize-api/repository/api/plantcaregarden.go
> +	file, _ := images[0].Open()
вот тут нужно что-то придумать -> нужно ограничиться вцелом одной фоткой

2023-10-16 22:13 UTC, themilchenko requested changes
Все хорошо, но креды бы надо спрятать.
А так в любом случае надо мерджится и соединять наши части как можно скорее

2023-10-16 22:13 UTC, themilchenko commented on configs/setup.yaml
> +  token: "2b109QtPNL155fUgf3usDHvsk"
Надо бы убрать перед тем, как мерджиться будем

2023-10-17 09:49 UTC, zeronethunter commented on configs/setup.yaml
> +  token: "2b109QtPNL155fUgf3usDHvsk"
нужен докер и секреты тогда, чтобы в пайплайне по секретам собирался контейнер и пушился в какой-нибудь регистри (лучше конечно в гитхабовский - он вроде бы бесплатный)

2023-10-17 09:58 UTC, themilchenko commented on configs/setup.yaml
> +  token: "2b109QtPNL155fUgf3usDHvsk"
тогда займусь этим

2023-10-17 19:35 UTC, merged